sudo: required

language: python

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}

services:
- docker

before_install:
- pip install docker-compose
- docker --version

script:
- make travis_compose_build
- make travis_compose_up
- make travis_compose_make_test
- make travis_run_audit

notifications:
  slack: scielo:6YcYDMh1STDOQT8H7umVuD0R
